plugins { id 'com.android.application' }

android {
    namespace 'com.example.plugin.sample'
    compileSdk 34
    defaultConfig {
        applicationId "com.example.plugin.sample"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    signingConfigs { debug }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }

    lint {
        checkReleaseBuilds false
        abortOnError false
    }

    compileOptions { sourceCompatibility 17; targetCompatibility 17 }
}

dependencies {
    compileOnly project(':api')          // 编译期可见，运行期由宿主提供
    compileOnly 'de.robv.android.xposed:api:82'
}
